version: "3.9"

services:
  # redis
  redis:
    image: redis:7
    container_name: redis_container_second
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # database postgres
  db:
    image: postgres:17
    container_name: postgres_container_second
    restart: always
    environment:
      POSTGRES_DB: nestjs_basic_login
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  redis_data:
  db_data:
